import type {
  AiOpenAICompatiblePresetId,
  AiProviderDescriptor,
  AiProviderId,
} from '../../../shared/types.js';

export const OPENAI_COMPATIBLE_PRESETS: Record<AiOpenAICompatiblePresetId, AiProviderDescriptor> = {
  openrouter: {
    id: 'openai-compatible',
    label: 'OpenRouter',
    presetId: 'openrouter',
    transport: 'openai-chat-completions',
    defaultModel: 'openai/gpt-4o-mini',
    baseUrl: 'https://openrouter.ai/api/v1',
    capabilities: ['chat', 'streaming', 'model-discovery', 'api-key'],
    requiresApiKey: true,
    local: false,
    modelDiscovery: true,
  },
  groq: {
    id: 'openai-compatible',
    label: 'Groq',
    presetId: 'groq',
    transport: 'openai-chat-completions',
    defaultModel: 'llama-3.3-70b-versatile',
    baseUrl: 'https://api.groq.com/openai/v1',
    capabilities: ['chat', 'streaming', 'model-discovery', 'api-key'],
    requiresApiKey: true,
    local: false,
    modelDiscovery: true,
  },
  mistral: {
    id: 'openai-compatible',
    label: 'Mistral',
    presetId: 'mistral',
    transport: 'openai-chat-completions',
    defaultModel: 'mistral-small-latest',
    baseUrl: 'https://api.mistral.ai/v1',
    capabilities: ['chat', 'streaming', 'model-discovery', 'api-key'],
    requiresApiKey: true,
    local: false,
    modelDiscovery: true,
  },
  together: {
    id: 'openai-compatible',
    label: 'Together',
    presetId: 'together',
    transport: 'openai-chat-completions',
    defaultModel: '',
    baseUrl: 'https://api.together.xyz/v1',
    capabilities: ['chat', 'streaming', 'model-discovery', 'api-key'],
    requiresApiKey: true,
    local: false,
    modelDiscovery: true,
  },
  fireworks: {
    id: 'openai-compatible',
    label: 'Fireworks',
    presetId: 'fireworks',
    transport: 'openai-chat-completions',
    defaultModel: '',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    capabilities: ['chat', 'streaming', 'model-discovery', 'api-key'],
    requiresApiKey: true,
    local: false,
    modelDiscovery: true,
  },
  'lm-studio': {
    id: 'openai-compatible',
    label: 'LM Studio',
    presetId: 'lm-studio',
    transport: 'openai-chat-completions',
    defaultModel: '',
    baseUrl: 'http://localhost:1234/v1',
    capabilities: ['chat', 'streaming', 'model-discovery', 'local'],
    requiresApiKey: false,
    local: true,
    modelDiscovery: true,
  },
  vllm: {
    id: 'openai-compatible',
    label: 'vLLM',
    presetId: 'vllm',
    transport: 'openai-chat-completions',
    defaultModel: '',
    baseUrl: 'http://localhost:8000/v1',
    capabilities: ['chat', 'streaming', 'model-discovery', 'local'],
    requiresApiKey: false,
    local: true,
    modelDiscovery: true,
  },
  'llama-cpp': {
    id: 'openai-compatible',
    label: 'llama.cpp',
    presetId: 'llama-cpp',
    transport: 'openai-chat-completions',
    defaultModel: '',
    baseUrl: 'http://localhost:8080/v1',
    capabilities: ['chat', 'streaming', 'model-discovery', 'local'],
    requiresApiKey: false,
    local: true,
    modelDiscovery: true,
  },
  localai: {
    id: 'openai-compatible',
    label: 'LocalAI',
    presetId: 'localai',
    transport: 'openai-chat-completions',
    defaultModel: '',
    baseUrl: 'http://localhost:8080/v1',
    capabilities: ['chat', 'streaming', 'model-discovery', 'local'],
    requiresApiKey: false,
    local: true,
    modelDiscovery: true,
  },
  custom: {
    id: 'openai-compatible',
    label: 'Custom OpenAI-compatible',
    presetId: 'custom',
    transport: 'openai-chat-completions',
    defaultModel: '',
    baseUrl: 'http://localhost:1234/v1',
    capabilities: ['chat', 'streaming', 'model-discovery'],
    requiresApiKey: false,
    local: false,
    modelDiscovery: true,
  },
};

export const AI_PROVIDER_DESCRIPTORS: AiProviderDescriptor[] = [
  {
    id: 'openai',
    label: 'OpenAI',
    transport: 'openai-responses',
    defaultModel: 'gpt-4.1-mini',
    capabilities: ['chat', 'streaming', 'model-discovery', 'api-key'],
    requiresApiKey: true,
    local: false,
    modelDiscovery: true,
  },
  {
    id: 'anthropic',
    label: 'Anthropic',
    transport: 'anthropic-messages',
    defaultModel: 'claude-sonnet-4-20250514',
    capabilities: ['chat', 'streaming', 'model-discovery', 'api-key'],
    requiresApiKey: true,
    local: false,
    modelDiscovery: true,
  },
  {
    id: 'ollama',
    label: 'Ollama',
    transport: 'ollama-chat',
    defaultModel: 'llama3.2',
    baseUrl: 'http://localhost:11434',
    capabilities: ['chat', 'streaming', 'model-discovery', 'local'],
    requiresApiKey: false,
    local: true,
    modelDiscovery: true,
  },
  ...Object.values(OPENAI_COMPATIBLE_PRESETS),
];

export function providerDescriptor(provider: AiProviderId): AiProviderDescriptor | undefined {
  return AI_PROVIDER_DESCRIPTORS.find((descriptor) => descriptor.id === provider && !descriptor.presetId);
}

export function openAICompatiblePreset(preset: AiOpenAICompatiblePresetId): AiProviderDescriptor {
  return OPENAI_COMPATIBLE_PRESETS[preset] ?? OPENAI_COMPATIBLE_PRESETS.custom;
}
